### ISSUE TITLE
Replace ActionBarSherlock and update Google Play Services

### ISSUE THREAD

**Issue by project-leader** [cireficc/git-waffle-example#2]
In order to integrate the Firebase dependency, we need to update Google Play Services to version 8 or higher. However, it has conflicts with ActionBarSherlock, so ABS needs to be removed and the app needs to be updated to use the standard APIs from AppCompat.

- [x] remove ActionBarSherlock
- [x] swap ABS and Android AppCompat dependencies
- [x] remove references to ABS and replace calls with AppCompat
- [x] fix residual issues with the migration

**Comment by cireficc** [comment]
This was a doozy, but it's finally done!
