### ISSUE TITLE
Missing meanings in Japanese

### ISSUE THREAD

**Issue by project-leader** [cireficc/git-waffle-example#4]
A lot of meanings are missing. For example, *train* missing noun meanings, *box* missing noun meanings, *shine* missing verb meanings. It seems that most words only show **one** meaning, when we know there are more.

**Comment by cireficc** [comment]
This was caused by Muncher overwriting the previous meanings with the same part of speech, so only the first meaning for each POS was exported. I fixed this by grouping the same POS before exporting them to our Vldict format.
