### ISSUE TITLE
Limit conjugations to approximately 50% of full conjugations

### ISSUE THREAD

**Issue by project-leader** [cireficc/git-waffle-example#9]
We are migrating to a subscription model; only include about 50% of the conjugations in the free version for unsubscribed users. Show *all* conjugations if the user is subscribed, or they have the paid version.

**Comment by cireficc** [comment]
The best solution is probably just to add the conjugation group *names* that we want to display into `LanguageDependentConstants`. That way, we can easily change them if we want to later.
